config/routes.rb
Rails.application.routes.draw do
  resources :flights
  resources :bookings, only: [:new, :show, :create, :destroy]
  resources :airports
  resources :passengers, only:[:new, :create, :destroy]

  root 'flights#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, class_name: 'Flight', foreign_key: 'from_airport_id'
  has_many :arriving_flights, class_name: 'Flight', foreign_key: 'to_airport_id'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers
  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :from_airport, class_name: 'Airport'
  belongs_to :to_airport, class_name: 'Airport'
  has_many :bookings
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking
  has_many :flights, through: :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @flight = Flight.find(params[:booking][:flight_id])
    @booking = Booking.new
    number_of_passengers = params[:booking][:number_of_passengers].to_i
    number_of_passengers.times do
      @booking.passengers.build
    end
  end

  def create
    @booking = Booking.new(booking_params)
    if @booking.save
      flash.notice = "Booking created!"
      PassengerMailer.with(booking_id: @booking.id).booking_confirmation.deliver_now
      redirect_to booking_path(@booking)
    else
      flash.notice = 'Fix errors!'
      render 'new'
    end
  end

  def show
    @booking = Booking.find(params[:id])
    @flight = Flight.find(@booking.flight_id)
    flash.notice = "Thanks for using Makemytrip"
  end

  private

  def booking_params
    params.require(:booking).permit(:flight_id,:number_of_passengers,passengers_attributes: [:suffix, :name, :email,:age])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: [:show, :edit, :update, :destroy]

  # GET /flights
  # GET /flights.json
  def index
    @airports = Airport.all
    if params[:search]
      @flights = Flight.where(from_airport_id: Airport.where(code: params[:search][:from_airport]),
                              to_airport_id: Airport.where(code: params[:search][:to_airport])
    ).order('time')
    else
      @flights = Flight.all
    end
  end

  # GET /flights/1
  # GET /flights/1.json
  def show
  end

  # GET /flights/new
  def new
    @flight = Flight.new
  end

  # GET /flights/1/edit
  def edit
  end

  # POST /flights
  # POST /flights.json
  def create
    @flight = Flight.new(flight_params)

    respond_to do |format|
      if @flight.save
        format.html { redirect_to @flight, notice: 'Flight was successfully created.' }
        format.json { render :show, status: :created, location: @flight }
      else
        format.html { render :new }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flights/1
  # PATCH/PUT /flights/1.json
  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to @flight, notice: 'Flight was successfully updated.' }
        format.json { render :show, status: :ok, location: @flight }
      else
        format.html { render :edit }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1
  # DELETE /flights/1.json
  def destroy
    @flight.destroy
    respond_to do |format|
      format.html { redirect_to flights_url, notice: 'Flight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def flight_params
      params.fetch(:flight, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<p id="notice"><%= notice %></p>
<div class ='container is-centered has-text-centered'>

  <div class ='container'>
    <h1 class ='heading'><br><br>Booking details: </h1>
  </div>

  <div class = 'container'>
    <table class ='table is-fullwidth is-bordered'>
      <thead>
        <tr>
          <th>Flight ID:</th>
          <th>Date</th>
          <th>Departure:</th>
          <th>Destination:</th>
          <th>Take off at:</th>
          <th>Duration(hours):</th>
          <th>Number of Passengers</th>
        </tr>
      </thead>

      <tbody>
          <tr>
            <th><%= @flight.id%></th>
            <th><%=params[:booking][:date]%></th>
            <th><%= @flight.from_airport.name%></th>
            <th><%=@flight.to_airport.name%></th>
            <th><%= @flight.time.strftime("%k:%M")%></th>
            <th><%=@flight.duration%></th>
            <th><%=@booking.number_of_passengers%>  </th>
          </tr>
      </tbody>
    </table>
  </div>
  <div class ='container'>
    <h1 class ='heading'><br> Please enter Passenger Details: </h1>
  </div>

  <div class ='container'>
    <%=simple_form_for(@booking) do |b|%>
    <%= b.error_notification%> <br>
      <%= b.fields_for (:passengers) do |p|%>
          <div class ='columns'>
            <div class = 'column'>
              <%= p.input :suffix,
                    collection: %w[Mr. Ms.],
                    input_html: {class: 'input', value:''},
                    wrapper: false,
                    label_html: {class: 'label'}
                    %>
            </div>
            <div class = 'column'>
              <%= p.input :name,
                    input_html: {class: 'input', value:''},
                    wrapper: false,
                    label_html: {class: 'label'}
                    %>
            </div>
            <div class = 'column'>
              <%= p.input :age,
                    input_html: {class: 'input', value:''},
                    wrapper: false,
                    label_html: {class: 'label'}
                    %>
            </div>
            <div class = 'column'>
              <%= p.input :email,
                    input_html: {class: 'input', value:''},
                    wrapper: false,
                    label_html: {class: 'label'}
                    %>
            </div>
          </div>
      <%end%>

        <div class = 'has-text-centered' >
          <%= b.hidden_field :number_of_passengers, value: params[:booking][:number_of_passengers]%>
          <%= b.hidden_field :date, value: params[:booking][:date]%>
          <%= b.hidden_field :flight_id, value: @flight.id%>
          <%= b.submit 'Submit',class: 'button is-large is-rounded' %>
        </div>
    <%end%>
  </div>


</div>

app/views/bookings/show.html.erb
<div class ='Section is-centered has-text-centered'>

  <div class ='container'>
    <h1 class ='heading'><br><br>Flight details: </h1>
  </div>

  <div class = 'container'>
    <table class ='table is-fullwidth is-bordered'>
      <thead>
        <tr>
          <th>Flight ID:</th>
          <th>Departure:</th>
          <th>Destination:</th>
          <th>Take off at:</th>
          <th>Duration(hours):</th>
        </tr>
      </thead>

      <tbody>
          <tr>
            <th><%= @flight.id%></th>
            <th><%= @flight.from_airport.name%></th>
            <th><%=@flight.to_airport.name%></th>
            <th><%= @flight.time.strftime("%k:%M")%></th>
            <th><%=@flight.duration%></th>
          </tr>
      </tbody>
    </table>
  </div>

  <div class ='container'>
    <h1 class ='heading'><br><br>Passenger details: </h1>
  </div>
  <div class = 'container'>
    <table class ='table is-fullwidth is-bordered'>
      <thead>
        <tr>
          <th>Suffix</th>
          <th>Name</th>
          <th>Age</th>
          <th>Email</th>
        </tr>
      </thead>
   
      <%@booking.passengers.each do |p|%>   
      <tbody>
          <tr>
            <th><%= p.suffix%></th>
            <th><%=p.name%></th>
            <th><%= p.age%></th>
            <th><%=p.email%></th>
          </tr>
      </tbody>
      <%end%>
    </table>
  </div>
</div>

app/views/flights/_flight_select.html.erb
<div class ='container is-centered has-text-centered'>
  <div class ='title is-3'>
  Available Flights:
  <div>

  <%= simple_form_for(:booking, method: :get, url: new_booking_path) do |b|%>
    <div class = 'section'>
      <table class ='table'>
        <thead>
          <tr>
            <th>Flight ID:</th>
            <th>Departure:</th>
            <th>Destination:</th>
            <th>Take off at:</th>
            <th>Duration(hours):</th>
            <th>Price (INR)</th>
            <th>Your Selection</th>
          </tr>
        </thead>

        <tbody>
          <% @flights.each do |flight|%>
            <tr>
              <th><%= flight.id%></th>
              <th><%= flight.from_airport.name%></th>
              <th><%=flight.to_airport.name%></th>
              <th><%= flight.time.strftime("%k:%M")%></th>
              <th><%=flight.duration%></th>
              <th><%=rand(2..9)*1000%></th>
              <th><%=b.radio_button 'flight_id', flight.id%>  </th>
            </tr>
          <%end%>
        </tbody>
      </table>
    </div>
    
    <div class = 'has-text-centered' >
      <%= b.hidden_field :number_of_passengers, value: params[:search][:number_of_passengers]%>
      <%= b.hidden_field :date, value: params[:search][:date]%>
      <%= b.submit 'Proceed to Details',class: 'button is-large is-rounded' %>
    </div>
  <%end%>
</div> 

app/views/flights/edit.html.erb
<h1>Editing Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Show', @flight %> |
<%= link_to 'Back', flights_path %>

app/views/flights/index.html.erb
<p id="notice"><%= notice %></p>
<div class = 'section'>
  <div class ='has-text-centered'>
    <h1 class = 'title is-2'><br>Search for Flights:</h1>
  </div>

  <div class ='container'>
    <%= simple_form_for(:search, method: :get, url: root_path) do |f|%>
    <%= f.error_notification%> <br>

      <div class ='columns'>
        <div class = 'column'>
          <%= f.input :from_airport,
                collection: Flight.all.map{|flight| flight.from_airport.code}.uniq,
                input_html: {class: 'input', value:''},
                placeholder: 'From City',
                wrapper: false,
                label_html: {class: 'label'}
                %>
        </div>
        <div class = 'column'>
          <%= f.input :to_airport,
                collection: Flight.all.map{|flight| flight.to_airport.code}.uniq,
                input_html: {class: 'input', value:''},
                placeholder: 'To City',
                wrapper: false,
                label_html: {class: 'label'}
                %>
        </div>
        <div class = 'column'>
          <%= f.input :number_of_passengers,
                collection: %w[1 2 3 4 5 6],
                input_html: {class: 'input', value:''},
                wrapper: false,
                label_html: {class: 'label'}
                %>
        </div>
        <div class = 'column'>
          <%= f.input :date,
                input_html: {class: 'input date', type: 'date', value:''},
                wrapper: false,
                label_html: {class: 'label'}
                %>
        </div>
      </div>
      <div class = 'has-text-centered' >
        <%= f.submit 'Search',class: 'button is-large is-rounded' %>
      </div>

    <%end%>
  </div>
</div>

<div class ='section'>
  <% if params[:search]%>
    <%= render 'flight_select'%>
  <%end%>
</div>

app/views/flights/new.html.erb
<h1>New Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Back', flights_path %>

app/views/flights/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_flight_path(@flight) %> |
<%= link_to 'Back', flights_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Makemytrip - Best travel booking site</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice]%>
      <div class='notification is-success global-notificaiton'>
        <p class="notice"><%= notice %></p>
      </div>
    <%end%>

    <% if flash[:alert]%>
      <div class='notification is-danger global-notificaiton'>
        <p class="alert"><%= alert %></p>
      </div>
    <%end%>

    <nav class = 'navbar is-fixed-top'>
      <div class = 'navbar-brand'>
        <%= link_to root_path, class: 'navbar-item' do%>
          <h1 class = 'title is-4' id = 'logo'>Makemytrip</h1>
        <%end%> 

        <div class ='navbar-burger burger' data-target = 'navbarExample'>
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>

      <div id = 'navbarExample' class ='navbar-menu'>
        <div class = 'navbar-end'>
          <div class = 'navbar-item'>
            <p>
              <div><%= link_to 'New booking', root_path, class: 'button' %></div>
            </p>
          </div>
        </div>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>